### ISSUE TITLE
Problem on ResolveFields

### ISSUE THREAD

**Issue by BR1G00** [measuredco/puck#670]
If you have 2 components, one with the resolveFields that we call "A" and one without, that uses the standard fields object "B", if you focus on A, then change focus on B and finally if you go back on A, the props of A doesn't reload and i still see the props of B.

resolveFields example where the error occurs:
`resolveFields: ({ props }, { changed, lastFields }) => {
    if (
      !changed.imageSource && !changed.id
    ) {
      return lastFields;
    }`

**Comment by chrisvxd** [comment]
This _might_ be fixed in #704. Would you be able to see if you can reproduce this with `0.17.0-canary.35170f8` when you get a moment?

**Comment by BR1G00** [comment]
Unfortunately, i can still reproduce it on `0.17.0-canary.35170f8`
